In [5]:
from datasets import load_dataset
import pandas as pd

In [21]:
eng_arc = load_dataset('allenai/ai2_arc', 'ARC-Challenge', split='test')
eng_arc

Dataset({
    features: ['id', 'question', 'choices', 'answerKey'],
    num_rows: 1172
})

In [22]:
eng_arc.to_pandas()

,id,question,choices,answerKey
0,Mercury_7175875,An astronomer observes that a planet rotates f...,"{'text': ['Planetary density will decrease.', ...",C
1,Mercury_SC_409171,A group of engineers wanted to know how differ...,"{'text': ['buildings will be built faster', 'b...",B
2,Mercury_SC_408547,The end result in the process of photosynthesi...,{'text': ['Chemical energy is absorbed through...,C
3,Mercury_407327,A physicist wants to determine the speed a car...,"{'text': ['the control', 'the hypothesis state...",D
4,MCAS_2006_9_44,An astronaut drops a 1.0 kg object and a 5.0 k...,{'text': ['They have each lost kinetic energy....,D
...,...,...,...,...
1167,MEA_2013_8_18,What is a similarity between sound waves and l...,"{'text': ['Both carry energy.', 'Both travel i...",A
1168,Mercury_7111125,Which of these is a response of cats to extern...,{'text': ['hairs on the back stand up when sca...,A
1169,LEAP_2009_8_10430,Which procedure best determines whether water ...,"{'text': ['Test three sugar cubes, one each in...",A
1170,Mercury_7165218,A student was asked to make a diagram showing ...,"{'text': ['island', 'plateau', 'rift', 'trench...",D
1171,MEA_2013_8_15,A ball is thrown downward onto a concrete floo...,"{'text': ['the floor', 'the pull of gravity', ...",A

In [23]:
llama_eus_examples = pd.read_json(
    "/gscratch5/users/asalem/cpt-ift/results/icl_benchmarks/meta-llama/Llama-3.1-8B/arc_eu_challenge/5-shot.json/meta-llama__Llama-3.1-8B/samples_arc_eu_challenge_2025-03-25T12-30-30.135362.jsonl",
    lines=True,
)

In [24]:
llama_eus_examples['doc_id_arc'] = llama_eus_examples['doc'].apply(lambda x: x['id'])

In [26]:
llama_eus_examples.merge(eng_arc.to_pandas(), left_on='doc_id_arc', right_on='id').to_csv("./llama_eus_arc_challenge.csv", index=False)

In [17]:
eus_ids = set(llama_eus_examples['doc_id_arc'].unique())
eng_ids = set(eng_arc.to_pandas()['id'].unique())

In [20]:
len(eus_ids), len(eng_ids), len(eus_ids.intersection(eng_ids))

(1172, 299, 0)

In [27]:
sample_df = pd.read_csv("/gscratch5/users/asalem/cpt-ift/scratch/sample.csv", header=0)
sample_df.head(5)

,doc_id,doc,resps,target,arguments,filtered_resps,doc_hash,prompt_hash,target_hash,acc,acc_norm,id,question,choices,answerKey
0,85,"{'id': 'MDSA_2009_8_2', 'question': 'Gure eguz...",0,{'gen_args_0': {'arg_0': 'Galdera: Izarok neur...,"[[['-1.0625', 'True']], [['-6.03125', 'False']...","[['-1.0625', 'True'], ['-6.03125', 'False'], [...",276d524befc2dc9c6b1963b16b3ee72db9ad2048c059c0...,c6ef89157d95b46f15048dd09d13033282528198f80c24...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,MDSA_2009_8_2,The period of rotation for each planet in our ...,"{'text': array(['24 hours', '28 days', '13 wee...",A
1,15,"{'id': 'Mercury_SC_413240', 'question': 'Zer t...","[[['-1.046875', 'True']], [['-6.09375', 'False...",0,{'gen_args_0': {'arg_0': 'Galdera: Ikasle bate...,"[['-1.046875', 'True'], ['-6.09375', 'False'],...",8783cbb66bf7c0c4df291bdf407f92d32f0cf7d9b13f72...,6dd29f8ba3e4ef4c54a4be6e9c8895ee387f724c87b093...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,Mercury_SC_413240,At which temperature does water freeze?,"{'text': array(['0 degrees Celsius', '32 degre...",A
2,14,"{'id': 'Mercury_7212993', 'question': 'Gas hau...","[[['-5.59375', 'False']], [['-3.078125', 'Fals...",2,{'gen_args_0': {'arg_0': 'Galdera: Zerrendatut...,"[['-5.59375', 'False'], ['-3.078125', 'False']...",14ca15638720a829886f053400157d46f48e8d5d19f909...,7ab62e6631d4cce3573d5ea3b058da325e305e20f672bc...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,0,Mercury_7212993,Which of these gases is the most abundant gree...,"{'text': array(['ozone', 'methane', 'water vap...",C
3,15,"{'id': 'Mercury_SC_413240', 'question': 'Zer t...",0,{'gen_args_0': {'arg_0': 'Galdera: Ikasle bate...,"[[['-1.046875', 'True']], [['-6.09375', 'False...","[['-1.046875', 'True'], ['-6.09375', 'False'],...",8783cbb66bf7c0c4df291bdf407f92d32f0cf7d9b13f72...,6dd29f8ba3e4ef4c54a4be6e9c8895ee387f724c87b093...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,Mercury_SC_413240,At which temperature does water freeze?,"{'text': array(['0 degrees Celsius', '32 degre...",A
4,24,"{'id': 'Mercury_SC_405086', 'question': 'Elurr...",1,{'gen_args_0': {'arg_0': 'Galdera: Tximistak e...,"[[['-12.8125', 'False']], [['-9.625', 'False']...","[['-12.8125', 'False'], ['-9.625', 'False'], [...",3704d27574ba3435f5094bd24bceb728a13678d9902a6d...,c437d1fd6d3e88d37e9844a2c33668645ba4d8c55ad01c...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,1,0,Mercury_SC_405086,"Snow, rain, hail, and fog are all forms of","{'text': array(['gas.', 'water.', 'wind.', 'cl...",B

In [28]:
arc_challenge_english = pd.read_json(
    "/gscratch5/users/asalem/cpt-ift/results/icl_benchmarks/meta-llama/Llama-3.1-8B/arc_challenge/5-shot.json/meta-llama__Llama-3.1-8B/samples_arc_challenge_2025-03-25T13-03-42.100702.jsonl",
    lines=True,
)
arc_challenge_english.head(5)

,doc_id,doc,target,arguments,resps,filtered_resps,doc_hash,prompt_hash,target_hash,acc,acc_norm
0,0,"{'id': 'Mercury_7175875', 'question': 'An astr...",2,{'gen_args_0': {'arg_0': 'Question: What is th...,"[[[-4.21875, False]], [[-2.59375, False]], [[-...","[[-4.21875, False], [-2.59375, False], [-0.220...",9ac07c0bf329749d60dea47e62236e71200f89791410eb...,1b831e373661eae66f6b739f82cf1854ea1b42ae76f77c...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1,1
1,1,"{'id': 'Mercury_SC_409171', 'question': 'A gro...",1,{'gen_args_0': {'arg_0': 'Question: Sooj learn...,"[[[-6.875, False]], [[-0.00958251953125, True]...","[[-6.875, False], [-0.00958251953125, True], [...",04bf654f45c33c5ba12c2e6eaa67bc85cbf8309a284346...,638b0ac58e82d0c1c1ecec0b0c8acad01f1b5d13ef0119...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,1,1
2,2,"{'id': 'Mercury_SC_408547', 'question': 'The e...",2,{'gen_args_0': {'arg_0': 'Question: Which of t...,"[[[-3.8125, False]], [[-3.8125, False]], [[-0....","[[-3.8125, False], [-3.8125, False], [-0.05810...",d4e72f52f4be5c51effc72d8decc44886564b4a262b4e4...,da0c3fb4ce342e2e418f7885a1ce6da25adbfb6786121f...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1,1
3,3,"{'id': 'Mercury_407327', 'question': 'A physic...",3,{'gen_args_0': {'arg_0': 'Question: A scientis...,"[[[-4.46875, False]], [[-5.09375, False]], [[-...","[[-4.46875, False], [-5.09375, False], [-2.718...",5618802c0774941e2a73290c8bf8f1f601db1896c970a2...,5e5e029683a28e9e344767042084975bdffc0827b36083...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,1,1
4,4,"{'id': 'MCAS_2006_9_44', 'question': 'An astro...",3,{'gen_args_0': {'arg_0': 'Question: Which type...,"[[[-2.015625, False]], [[-1.5234375, False]], ...","[[-2.015625, False], [-1.5234375, False], [-1....",4d6472aed0241ca5ca9f75731427f68f1963db9f90562c...,3237fdd3bbd9db9f14d919d5b5a71cdf0255bea4dfa9f1...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0,0

In [29]:
arc_challenge_english['doc_id_arc'] = arc_challenge_english['doc'].apply(lambda x: x['id'])

In [32]:
arc_challenge_english.merge(sample_df, left_on='doc_id_arc', right_on='id', suffixes=["eng", "eus"]).to_csv("./llama_eng_arc_challenge.csv", index=False)

In [33]:
# sample 
sample = pd.read_csv("./llama_eng_arc_challenge.csv", header=0)
sample.head(5)

,doc_ideng,doceng,targeteng,argumentseng,respseng,filtered_respseng,doc_hasheng,prompt_hasheng,target_hasheng,acceng,...,filtered_respseus,doc_hasheus,prompt_hasheus,target_hasheus,acceus,acc_normeus,id,question,choices,answerKey
0,9,"{'id': 'MCAS_2003_8_11', 'question': 'Copper i...",0,{'gen_args_0': {'arg_0': 'Question: Which best...,"[[['-0.01214599609375', 'True']], [['-5.875', ...","[['-0.01214599609375', 'True'], ['-5.875', 'Fa...",ef09e15aeee390652d803ec569f8cd31019f5975857780...,956e07237313cae268727961e3f34ffedd60acfaba1297...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,...,"[['-1.265625', 'True'], ['-9.25', 'False'], ['...",5aa6bd5a680c08307a74df6633c4889c86240a748930e1...,90639c7e8768414db5524efa9f9bbf47fbe53ce9a3ce0b...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,MCAS_2003_8_11,Copper is an element that is used in electrica...,"{'text': array(['the atom', 'the electron', 't...",A
1,14,"{'id': 'Mercury_7212993', 'question': 'Which o...",2,{'gen_args_0': {'arg_0': 'Question: Animals ma...,"[[['-4.71875', 'False']], [['-5.09375', 'False...","[['-4.71875', 'False'], ['-5.09375', 'False'],...",f750462e3130c5ae97d08e93844ba08df0a602ec970109...,3c06c503c91f423550edf58efb11c22a9e6fdaa6d3b9ce...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1,...,"[['-5.59375', 'False'], ['-3.078125', 'False']...",14ca15638720a829886f053400157d46f48e8d5d19f909...,7ab62e6631d4cce3573d5ea3b058da325e305e20f672bc...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,0,Mercury_7212993,Which of these gases is the most abundant gree...,"{'text': array(['ozone', 'methane', 'water vap...",C
2,15,"{'id': 'Mercury_SC_413240', 'question': 'At wh...",0,{'gen_args_0': {'arg_0': 'Question: A student ...,"[[['-0.0693359375', 'True']], [['-3.0625', 'Fa...","[['-0.0693359375', 'True'], ['-3.0625', 'False...",c7dd929e37311e596dac9c1c1f9ce0129f789a40e228d4...,e384a97d11b93c85e7657c2133185c653b5c64dfad4eb6...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,...,"[['-1.046875', 'True'], ['-6.09375', 'False'],...",8783cbb66bf7c0c4df291bdf407f92d32f0cf7d9b13f72...,6dd29f8ba3e4ef4c54a4be6e9c8895ee387f724c87b093...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,Mercury_SC_413240,At which temperature does water freeze?,"{'text': array(['0 degrees Celsius', '32 degre...",A
3,15,"{'id': 'Mercury_SC_413240', 'question': 'At wh...",0,{'gen_args_0': {'arg_0': 'Question: A student ...,"[[['-0.0693359375', 'True']], [['-3.0625', 'Fa...","[['-0.0693359375', 'True'], ['-3.0625', 'False...",c7dd929e37311e596dac9c1c1f9ce0129f789a40e228d4...,e384a97d11b93c85e7657c2133185c653b5c64dfad4eb6...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,...,"[['-1.046875', 'True'], ['-6.09375', 'False'],...",8783cbb66bf7c0c4df291bdf407f92d32f0cf7d9b13f72...,6dd29f8ba3e4ef4c54a4be6e9c8895ee387f724c87b093...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,Mercury_SC_413240,At which temperature does water freeze?,"{'text': array(['0 degrees Celsius', '32 degre...",A
4,24,"{'id': 'Mercury_SC_405086', 'question': 'Snow,...",1,{'gen_args_0': {'arg_0': 'Question: Many ferti...,"[[['-6.625', 'False']], [['-0.005950927734375'...","[['-6.625', 'False'], ['-0.005950927734375', '...",98a8c3914c8d7b742233ca91b15fb5bd240609ea08a8af...,16f16300fb2f04224549916f7ac0575346f4ee72a1f8b9...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,1,...,"[['-12.8125', 'False'], ['-9.625', 'False'], [...",3704d27574ba3435f5094bd24bceb728a13678d9902a6d...,c437d1fd6d3e88d37e9844a2c33668645ba4d8c55ad01c...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,1,0,Mercury_SC_405086,"Snow, rain, hail, and fog are all forms of","{'text': array(['gas.', 'water.', 'wind.', 'cl...",B

In [39]:
latxa = pd.read_json(
    "/gscratch5/users/asalem/cpt-ift/results/icl_benchmarks/Latxa3.1_8b_lr1e-5/arc_eu_challenge/5-shot.json/__proiektuak__ikergaitu-data__azabala106__model_evaluation__trained_models__Latxa3.1_8b_lr1e-5/samples_arc_eu_challenge_2025-03-25T13-38-35.293643.jsonl",
    lines=True,
)

In [40]:
latxa['doc_id_arc'] = latxa['doc'].apply(lambda x: x['id'])

In [41]:
latxa.merge(sample, left_on='doc_id_arc', right_on='id', suffixes=["latxa", "llama"]).to_csv("./llama_latxa_arc_challenge.csv", index=False)

In [42]:
latxa

,doc_id,doc,target,arguments,resps,filtered_resps,doc_hash,prompt_hash,target_hash,acc,acc_norm,doc_id_arc
0,0,"{'id': 'Mercury_7175875', 'question': 'Astrono...",2,{'gen_args_0': {'arg_0': 'Galdera: Itziarri mi...,"[[[-21.75, False]], [[-27.75, False]], [[-20.5...","[[-21.75, False], [-27.75, False], [-20.5, Fal...",e6229a397989b82d30143d027e111e3bc2353052fb74a8...,d09526cdd1f48894c9d9077586b250e96e09adade82c54...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,1,1,Mercury_7175875
1,1,"{'id': 'Mercury_SC_409171', 'question': 'Ingen...",1,{'gen_args_0': {'arg_0': 'Galdera: Gizaki bate...,"[[[-17.625, False]], [[-15.0, False]], [[-29.7...","[[-17.625, False], [-15.0, False], [-29.75, Fa...",cc0ecbfaf993b9e234b4242cae7c8dbc5869310b1e838c...,0e028ca370be6b308bf821bd3ec083c2a36ce4a06a8728...,6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d...,1,1,Mercury_SC_409171
2,2,"{'id': 'Mercury_SC_408547', 'question': 'Fotos...",2,{'gen_args_0': {'arg_0': 'Galdera: Ikasle bate...,"[[[-25.875, False]], [[-13.1875, False]], [[-2...","[[-25.875, False], [-13.1875, False], [-22.375...",adf10fd4d46fa1fdfe8676eff918b10555f0d6d800130b...,d9654371f1210c67d6ca793be1188e9ddfa81c09e7b234...,d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f...,0,0,Mercury_SC_408547
3,3,"{'id': 'Mercury_407327', 'question': 'Fisikari...",3,{'gen_args_0': {'arg_0': 'Galdera: Nola aldatu...,"[[[-11.75, False]], [[-19.75, False]], [[-32.5...","[[-11.75, False], [-19.75, False], [-32.5, Fal...",30add95040f09de1762da9624de4e28469fc5b1236c71b...,b9e56b1bf9f75871bc3b8fabd158519471202f1b6249a6...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0,1,Mercury_407327
4,4,"{'id': 'MCAS_2006_9_44', 'question': 'Astronau...",3,{'gen_args_0': {'arg_0': 'Galdera: Hauetako ze...,"[[[-23.25, False]], [[-29.375, False]], [[-26....","[[-23.25, False], [-29.375, False], [-26.625, ...",5a1b87c408a6cd226c8171dfa34725faa644ed59a60e0b...,8031957c9d157ca67898fef3099a360f65da64f08df94b...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,0,0,MCAS_2006_9_44
...,...,...,...,...,...,...,...,...,...,...,...,...
1167,1167,"{'id': 'MEA_2013_8_18', 'question': 'Zer antze...",0,{'gen_args_0': {'arg_0': 'Galdera: Materiaren ...,"[[[-11.75, False]], [[-14.75, False]], [[-21.6...","[[-11.75, False], [-14.75, False], [-21.625, F...",1877322924ce28cc2a9757c2db8af73c7c3c4b9efa0998...,8013eab7e4d9f7fa5ddb1b2b2b4282012ba8f383c6e767...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,MEA_2013_8_18
1168,1168,"{'id': 'Mercury_7111125', 'question': 'Hauetak...",0,{'gen_args_0': {'arg_0': 'Galdera: Bi klasetak...,"[[[-34.25, False]], [[-26.5, False]], [[-36.5,...","[[-34.25, False], [-26.5, False], [-36.5, Fals...",2718ef8d5fc364cf5cec22a24c749d65802ac0d18fdb6e...,d499e6820eba91d28f425bc38592d365deb0a1823b5e7f...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,0,0,Mercury_7111125
1169,1169,"{'id': 'LEAP_2009_8_10430', 'question': 'Hauet...",0,{'gen_args_0': {'arg_0': 'Galdera: Klima-aldak...,"[[[-38.0, False]], [[-42.25, False]], [[-45.5,...","[[-38.0, False], [-42.25, False], [-45.5, Fals...",370e553131cf136e7299ce69bdf0504e0628d181737a8f...,c1a9e486e950c989ee88b44951b1eb09881d543ccb3765...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,1,LEAP_2009_8_10430
1170,1170,"{'id': 'Mercury_7165218', 'question': 'Ikasle ...",3,{'gen_args_0': {'arg_0': 'Galdera: Ikasle-tald...,"[[[-15.5625, False]], [[-16.25, False]], [[-20...","[[-15.5625, False], [-16.25, False], [-20.0, F...",eb549a0f8f8e29b6e9358187f07d49976f989ee810733b...,cfe46e770d6dec497a2b47eea85fef7a0c7d6a14c66c5c...,4e07408562bedb8b60ce05c1decfe3ad16b72230967de0...,1,1,Mercury_7165218
1171,1171,"{'id': 'MEA_2013_8_15', 'question': 'Pilota ba...",0,{'gen_args_0': {'arg_0': 'Galdera: Osagai haue...,"[[[-3.828125, False]], [[-11.5625, False]], [[...","[[-3.828125, False], [-11.5625, False], [-33.2...",bfe29bf51f1b89f9fc7d779c6a33a697204a418eae29d7...,3ffc749d5e1e1e3ce398b75d3f61558ffe2ae2530af25f...,5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91...,1,0,MEA_2013_8_15